using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace LeshanTicketSystem.UI
{
    public class ColorHelper
    {
        /// <summary>
        /// 获取所有可用的颜色列表
        /// </summary>
        /// <returns>颜色列表</returns>
        public static List<Color> GetAllColorList()
        {
            var result = new List<Color>
        {
            Color.MediumAquamarine,
            Color.MediumBlue,
            Color.MediumOrchid,
            Color.MediumPurple,
            Color.MediumSeaGreen,
            Color.MediumSlateBlue,
            Color.MediumSpringGreen,
            Color.MediumTurquoise,
            Color.MediumVioletRed,
            Color.MidnightBlue,
            Color.MintCream,
            Color.MistyRose,
            Color.Moccasin,
            Color.Navy,
            Color.OldLace,
            Color.Olive,
            Color.Maroon,
            Color.OliveDrab,
            Color.Magenta,
            Color.LimeGreen,
            Color.LavenderBlush,
            Color.LawnGreen,
            Color.LemonChiffon,
            Color.LightBlue,
            Color.LightCoral,
            Color.LightCyan,
            Color.LightGoldenrodYellow,
            Color.LightGray,
            Color.LightGreen,
            Color.LightPink,
            Color.LightSalmon,
            Color.LightSeaGreen,
            Color.LightSkyBlue,
            Color.LightSlateGray,
            Color.LightSteelBlue,
            Color.LightYellow,
            Color.Lime,
            Color.Linen,
            Color.Yellow,
            Color.Orange,
            Color.Orchid,
            Color.Silver,
            Color.SkyBlue,
            Color.SlateBlue,
            Color.SlateGray,
            Color.Snow,
            Color.SpringGreen,
            Color.SteelBlue,
            Color.Tan,
            Color.Teal,
            Color.Thistle,
            Color.Tomato,
            Color.Transparent,
            Color.Turquoise,
            Color.Violet,
            Color.Wheat,
            Color.Sienna,
            Color.OrangeRed,
            Color.SeaShell,
            Color.SandyBrown,
            Color.PaleGoldenrod,
            Color.PaleGreen,
            Color.PaleTurquoise,
            Color.PaleVioletRed,
            Color.PapayaWhip,
            Color.PeachPuff,
            Color.Peru,
            Color.Pink,
            Color.Plum,
            Color.PowderBlue,
            Color.Purple,
            Color.RebeccaPurple,
            Color.Red,
            Color.RosyBrown,
            Color.RoyalBlue,
            Color.SaddleBrown,
            Color.Salmon,
            Color.SeaGreen,
            Color.Khaki,
            Color.Lavender,
            Color.Cyan,
            Color.DarkMagenta,
            Color.DarkKhaki,
            Color.DarkGreen,
            Color.DarkGray,
            Color.DarkGoldenrod,
            Color.DarkCyan,
            Color.DarkBlue,
            Color.Ivory,
            Color.Crimson,
            Color.Cornsilk,
            Color.CornflowerBlue,
            Color.Coral,
            Color.Chocolate,
            Color.DarkOliveGreen,
            Color.Chartreuse,
            Color.BurlyWood,
            Color.Brown,
            Color.BlueViolet,
            Color.Blue,
            Color.BlanchedAlmond,
            Color.Black,
            Color.Bisque,
            Color.Beige,
            Color.Azure,
            Color.Aquamarine,
            Color.Aqua,
            Color.AntiqueWhite,
            Color.AliceBlue,
            Color.CadetBlue,
            Color.DarkOrange,
            Color.YellowGreen,
            Color.DarkRed,
            Color.Indigo,
            Color.IndianRed,
            Color.DarkOrchid,
            Color.Honeydew,
            Color.GreenYellow,
            Color.Green,
            Color.Gray,
            Color.Goldenrod,
            Color.Gold,
            Color.GhostWhite,
            Color.Gainsboro,
            Color.Fuchsia,
            Color.ForestGreen,
            Color.HotPink,
            Color.Firebrick,
            Color.FloralWhite,
            Color.DodgerBlue,
            Color.DimGray,
            Color.DeepSkyBlue,
            Color.DeepPink,
            Color.DarkViolet,
            Color.DarkTurquoise,
            Color.DarkSlateGray,
            Color.DarkSlateBlue,
            Color.DarkSeaGreen,
            Color.DarkSalmon
        };

            return result;
        }
    }
}
